

version: 0.2

phases:
  pre_build:
    commands:
      - whoami
      - echo $PATH
      - ls -la /usr/bin/node
      - node -v
      - service docker start
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION | sed -e 's/-e none//g')
      -  REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
  build:
    commands:
      - cd ./frontend
      - pwd
      - echo Frontend Build started on `date`
      - node -v
      - npm -v
      - npm install
      - npm run build
      - echo Frontend Build finished on `date`
      - cd ../backend
      - echo Backend Build started on `date`
      - npm install
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - cd ..
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - printf '[{"name":"%s","imageUri":"%s"}]' $ECS_CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
      - echo Pushing files to S3
      - aws s3 cp ./frontend/build s3://games.schematical.com/ --recursive --acl public-read
artifacts:
  files:
    - imagedefinitions.json