

version: 0.2

phases:
  pre_build:
    commands:
      - pwd
      - service docker start
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION | sed -e 's/-e none//g')
  build:
    commands:
      - cd ./frontend
      - pwd
      - echo Frontend Build started on `date`
      - npm install
      - npm run build
      - echo Frontend Build finished on `date`
      - cd ../backend
      - echo Backend Build started on `date`
      - npm install
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
artifacts:
  files:
    - '**/*'
  base-directory: 'frontend/build*'
  discard-paths:
    no
