

version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - pwd
      - cd ./frontend
  build:
    commands:
      - pwd
      - echo Build started on `date`
      - npm install
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - cd dist
      #- zip -r ../app.zip ./*
      #- cd ../
      - pwd
      - ls

      # - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
artifacts:
  files:
    - '**/*'
  base-directory: 'build*'
  discard-paths:
    no
